/**
 * unplugin-based build plugin + inline AST code generator
 *
 * Since Node ESM cannot resolve .ts internal imports,
 * the codegen logic is included directly in this file.
 *
 * Supports Vite, webpack, Rollup, and esbuild.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { parseSync } from '@swc/core';
import { createUnplugin } from 'unplugin';

// ─── Codegen Types ────────────────────────────────────────

interface ClassInfo {
	className: string;
	namespace: string;
	filePath: string;
}

interface FnInfo {
	exportName: string;
	namespace: string;
	method: string;
	filePath: string;
}

interface GenerateOptions {
	dirs: string[];
	outputFile: string;
	/** Resolved absolute path for the client file, or false to skip */
	clientFile?: string | false;
}

// ─── File Discovery ───────────────────────────────────────

function findTsFiles(dir: string): string[] {
	if (!existsSync(dir)) return [];
	const results: string[] = [];
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const fullPath = join(dir, entry.name);
		if (entry.isDirectory()) {
			results.push(...findTsFiles(fullPath));
		} else if (
			entry.name.endsWith('.ts') &&
			!entry.name.endsWith('.d.ts') &&
			!entry.name.endsWith('.gen.ts') &&
			entry.name !== 'ipc.client.ts'
		) {
			results.push(fullPath);
		}
	}
	return results.sort();
}

// ─── AST Parsing ────────────────────────────────────────

function parseClassHandlers(filePath: string, content: string): ClassInfo[] {
	const ast = parseSync(content, { syntax: 'typescript', decorators: true });
	const results: ClassInfo[] = [];

	for (const item of ast.body) {
		// biome-ignore lint/suspicious/noExplicitAny: SWC AST node dynamic access
		const node = item as any;
		let classDecl = null;

		if (node.type === 'ExportDeclaration' && node.declaration?.type === 'ClassDeclaration') {
			classDecl = node.declaration;
		} else if (node.type === 'ExportDefaultDeclaration' && node.decl?.type === 'ClassDeclaration') {
			classDecl = node.decl;
		}

		if (!classDecl?.decorators?.length) continue;

		for (const decorator of classDecl.decorators) {
			const expr = decorator.expression;
			if (expr?.type !== 'CallExpression') continue;
			if (expr.callee?.type !== 'Identifier' || expr.callee.value !== 'ipcClass') continue;
			const firstArg = expr.arguments?.[0]?.expression;
			if (firstArg?.type !== 'StringLiteral') continue;

			results.push({
				namespace: firstArg.value,
				className: classDecl.identifier.value,
				filePath,
			});
		}
	}

	return results;
}

function parseFnHandlers(filePath: string, content: string): FnInfo[] {
	const ast = parseSync(content, { syntax: 'typescript', decorators: true });
	const results: FnInfo[] = [];

	for (const item of ast.body) {
		// biome-ignore lint/suspicious/noExplicitAny: SWC AST node dynamic access
		const node = item as any;
		if (node.type !== 'ExportDeclaration') continue;
		const decl = node.declaration;
		if (decl?.type !== 'VariableDeclaration') continue;

		for (const declarator of decl.declarations) {
			if (declarator.id?.type !== 'Identifier') continue;
			const init = declarator.init;
			if (init?.type !== 'CallExpression') continue;
			if (init.callee?.type !== 'Identifier' || init.callee.value !== 'ipcHandler') continue;
			const firstArg = init.arguments?.[0]?.expression;
			if (firstArg?.type !== 'StringLiteral') continue;

			const channel = firstArg.value as string;
			const colonIdx = channel.indexOf(':');
			results.push({
				exportName: declarator.id.value,
				namespace: colonIdx >= 0 ? channel.slice(0, colonIdx) : channel,
				method: colonIdx >= 0 ? channel.slice(colonIdx + 1) : channel,
				filePath,
			});
		}
	}

	return results;
}

// ─── Code Generation ───────────────────────────────────

function toImportPath(outputDir: string, filePath: string): string {
	let rel = relative(outputDir, filePath).replace(/\.ts$/, '').split(sep).join('/');
	if (!rel.startsWith('.')) rel = `./${rel}`;
	return rel;
}

function generate(options: GenerateOptions): void {
	const allClasses: ClassInfo[] = [];
	const allFns: FnInfo[] = [];

	for (const dir of options.dirs) {
		for (const file of findTsFiles(dir)) {
			const content = readFileSync(file, 'utf-8');
			allClasses.push(...parseClassHandlers(file, content));
			allFns.push(...parseFnHandlers(file, content));
		}
	}

	const outputDir = dirname(options.outputFile);
	if (!existsSync(outputDir)) {
		mkdirSync(outputDir, { recursive: true });
	}

	const lines: string[] = ['/* Auto-generated by electron-ipc-handler — DO NOT EDIT */', ''];

	// side-effect imports
	const sideEffectPaths = new Set<string>();
	for (const c of allClasses) sideEffectPaths.add(toImportPath(outputDir, c.filePath));
	for (const f of allFns) sideEffectPaths.add(toImportPath(outputDir, f.filePath));
	for (const path of sideEffectPaths) {
		lines.push(`import '${path}';`);
	}
	lines.push('');

	// re-export
	lines.push("export { registerIpcDecoratorHandler } from 'electron-ipc-handler';");
	lines.push('');

	// type imports — Biome compatible (merged + alphabetical)
	const typeImportMap = new Map<string, Set<string>>();
	const addTypeImport = (path: string, name: string) => {
		if (!typeImportMap.has(path)) typeImportMap.set(path, new Set());
		typeImportMap.get(path)?.add(name);
	};

	if (allClasses.length > 0) {
		addTypeImport("'electron-ipc-handler'", 'InferApi');
	}
	if (allFns.length > 0) {
		addTypeImport("'electron-ipc-handler'", 'ExtractIpcFn');
	}
	for (const c of allClasses) {
		addTypeImport(`'${toImportPath(outputDir, c.filePath)}'`, c.className);
	}
	for (const f of allFns) {
		addTypeImport(`'${toImportPath(outputDir, f.filePath)}'`, f.exportName);
	}
	if (typeImportMap.size > 0) {
		const sortedPaths = [...typeImportMap.keys()].sort();
		for (const path of sortedPaths) {
			const names = typeImportMap.get(path);
			if (!names) continue;
			const sorted = [...names].sort();
			lines.push(`import type { ${sorted.join(', ')} } from ${path};`);
		}
		lines.push('');
	}

	// IpcApi type
	const typeParts: string[] = [];

	if (allClasses.length > 0) {
		const entries = allClasses.map((c) => `\t${c.namespace}: ${c.className};`).join('\n');
		typeParts.push(`InferApi<{\n${entries}\n}>`);
	}

	const fnByNs = new Map<string, FnInfo[]>();
	for (const f of allFns) {
		if (!fnByNs.has(f.namespace)) fnByNs.set(f.namespace, []);
		fnByNs.get(f.namespace)?.push(f);
	}
	if (fnByNs.size > 0) {
		const nsBlocks: string[] = [];
		for (const [ns, fns] of fnByNs) {
			const methods = fns
				.map((f) => `\t\t${f.method}: ExtractIpcFn<typeof ${f.exportName}>;`)
				.join('\n');
			nsBlocks.push(`\t${ns}: {\n${methods}\n\t};`);
		}
		typeParts.push(`{\n${nsBlocks.join('\n')}\n}`);
	}

	lines.push(
		typeParts.length > 0
			? `export type IpcApi = ${typeParts.join(' & ')};`
			: 'export type IpcApi = Record<string, never>;'
	);
	lines.push('');

	const content = lines.join('\n');

	const genChanged =
		!existsSync(options.outputFile) || readFileSync(options.outputFile, 'utf-8') !== content;

	if (genChanged) {
		writeFileSync(options.outputFile, content);
	}

	// Generate client file for renderer convenience (always check, even if gen file unchanged)
	if (options.clientFile !== false) {
		generateClient(options.outputFile, options.clientFile);
	}
}

function generateClient(genFile: string, customPath?: string): void {
	const clientFile = customPath ?? join(dirname(genFile), 'ipc.client.ts');
	const clientDir = dirname(clientFile);

	if (!existsSync(clientDir)) {
		mkdirSync(clientDir, { recursive: true });
	}

	const genRelative = relative(clientDir, genFile).replace(/\.ts$/, '').split(sep).join('/');
	const genImportPath = genRelative.startsWith('.') ? genRelative : `./${genRelative}`;

	const clientLines = [
		'/* Auto-generated by electron-ipc-handler — DO NOT EDIT */',
		'',
		"import { createIpcClient } from 'electron-ipc-handler';",
		`import type { IpcApi } from '${genImportPath}';`,
		'',
		'export const ipc = createIpcClient<IpcApi>();',
		'',
	];

	const clientContent = clientLines.join('\n');

	if (existsSync(clientFile)) {
		const existing = readFileSync(clientFile, 'utf-8');
		if (existing === clientContent) return;
	}

	writeFileSync(clientFile, clientContent);
}

// ─── unplugin Factory ────────────────────────────────────

export interface IpcDecoratorOptions {
	/** Directories to scan (relative to project root) */
	dirs: string[];
	/** Output file path (relative to project root) */
	output: string;
	/** true = client next to gen file, string = custom output path, false = skip (default: true) */
	client?: boolean | string;
}

export const ipcDecoratorPlugin = createUnplugin<IpcDecoratorOptions>((options) => {
	let root = process.cwd();
	let resolvedDirs: string[] = [];
	let outputFile = '';
	let clientFile: string | false = false;

	function resolvePaths(): void {
		resolvedDirs = options.dirs.map((d) => resolve(root, d));
		outputFile = resolve(root, options.output);
		if (typeof options.client === 'string') {
			clientFile = resolve(root, options.client);
		} else if (options.client !== false) {
			clientFile = join(dirname(outputFile), 'ipc.client.ts');
		}
	}

	return {
		name: 'electron-ipc-handler',

		// Vite-specific hook
		vite: {
			configResolved(config: { root: string }) {
				root = config.root;
				resolvePaths();
			},
		},

		buildStart() {
			if (!resolvedDirs.length) resolvePaths();

			if (typeof this.addWatchFile === 'function') {
				for (const dir of resolvedDirs) {
					if (existsSync(dir)) this.addWatchFile(dir);
				}
			}

			generate({ dirs: resolvedDirs, outputFile, clientFile });
		},

		watchChange(id: string) {
			if (!resolvedDirs.length) return;
			const isTarget = resolvedDirs.some((dir) => id.startsWith(dir));
			if (isTarget && id.endsWith('.ts')) {
				generate({ dirs: resolvedDirs, outputFile, clientFile });
			}
		},
	};
});

// Loose return types to avoid Plugin type conflicts across bundler versions,
// so consumers don't need `as PluginOption` casts.

// biome-ignore lint/suspicious/noExplicitAny: vite Plugin type compatibility
export const vite: (options: IpcDecoratorOptions) => any = ipcDecoratorPlugin.vite;

// biome-ignore lint/suspicious/noExplicitAny: webpack Plugin type compatibility
export const webpack: (options: IpcDecoratorOptions) => any = ipcDecoratorPlugin.webpack;

// biome-ignore lint/suspicious/noExplicitAny: rollup Plugin type compatibility
export const rollup: (options: IpcDecoratorOptions) => any = ipcDecoratorPlugin.rollup;

// biome-ignore lint/suspicious/noExplicitAny: esbuild Plugin type compatibility
export const esbuild: (options: IpcDecoratorOptions) => any = ipcDecoratorPlugin.esbuild;
