import { existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

// We test the generate logic indirectly via the plugin's buildStart
import { ipcDecoratorPlugin } from './unplugin';

const FIXTURE_DIR = resolve(import.meta.dirname, '__fixtures__');
const HANDLERS_DIR = join(FIXTURE_DIR, 'handlers');
const OUTPUT_FILE = join(FIXTURE_DIR, 'ipc', 'generated.ts');

describe('unplugin', () => {
	beforeEach(() => {
		mkdirSync(HANDLERS_DIR, { recursive: true });
	});

	afterEach(() => {
		if (existsSync(FIXTURE_DIR)) {
			rmSync(FIXTURE_DIR, { recursive: true });
		}
	});

	function writeHandler(name: string, content: string) {
		writeFileSync(join(HANDLERS_DIR, name), content);
	}

	function buildPlugin() {
		const raw = ipcDecoratorPlugin.raw(
			{ dirs: [HANDLERS_DIR], output: OUTPUT_FILE },
			{ framework: 'vite' }
		);

		// unplugin raw returns object(s) with buildStart
		const plugin = Array.isArray(raw) ? raw[0] : raw;

		// Simulate vite configResolved
		if (plugin.vite?.configResolved) {
			plugin.vite.configResolved({ root: FIXTURE_DIR });
		}

		// Call buildStart with minimal context
		plugin.buildStart?.call({ addWatchFile: () => {} });
	}

	it('generates output from @ipcClass decorator', () => {
		writeHandler(
			'user.controller.ts',
			`
import { ipcClass, ipcMethod } from 'electron-ipc-handler/main';

@ipcClass('users')
export class UserController {
	@ipcMethod()
	getAll() { return []; }
}
`
		);

		buildPlugin();

		expect(existsSync(OUTPUT_FILE)).toBe(true);
		const content = readFileSync(OUTPUT_FILE, 'utf-8');

		expect(content).toContain('Auto-generated by electron-ipc-handler');
		expect(content).toContain("import '../handlers/user.controller';");
		expect(content).toContain(
			"export { registerIpcDecoratorHandler } from 'electron-ipc-handler';"
		);
		expect(content).toContain('UserController');
		expect(content).toContain('InferApi');
		expect(content).toContain('users: UserController');
	});

	it('generates output from ipcHandler function', () => {
		writeHandler(
			'system.handler.ts',
			`
import { ipcHandler } from 'electron-ipc-handler/main';

export const ping = ipcHandler('system:ping', () => 'pong');
`
		);

		buildPlugin();

		const content = readFileSync(OUTPUT_FILE, 'utf-8');

		expect(content).toContain("import '../handlers/system.handler';");
		expect(content).toContain('ExtractIpcFn');
		expect(content).toContain('ping');
		expect(content).toContain('system:');
	});

	it('handles mixed class and function handlers', () => {
		writeHandler(
			'user.controller.ts',
			`
import { ipcClass, ipcMethod } from 'electron-ipc-handler/main';

@ipcClass('users')
export class UserController {
	@ipcMethod()
	getAll() { return []; }
}
`
		);
		writeHandler(
			'system.handler.ts',
			`
import { ipcHandler } from 'electron-ipc-handler/main';

export const ping = ipcHandler('system:ping', () => 'pong');
`
		);

		buildPlugin();

		const content = readFileSync(OUTPUT_FILE, 'utf-8');

		expect(content).toContain('InferApi');
		expect(content).toContain('ExtractIpcFn');
		expect(content).toContain('UserController');
		expect(content).toContain('ping');
	});

	it('generates empty IpcApi when no handlers found', () => {
		buildPlugin();

		const content = readFileSync(OUTPUT_FILE, 'utf-8');

		expect(content).toContain('export type IpcApi = Record<string, never>;');
	});

	it('skips .d.ts files', () => {
		writeHandler('types.d.ts', 'export type Foo = string;');
		writeHandler(
			'real.ts',
			`
import { ipcHandler } from 'electron-ipc-handler/main';
export const check = ipcHandler('health:check', () => 'ok');
`
		);

		buildPlugin();

		const content = readFileSync(OUTPUT_FILE, 'utf-8');

		expect(content).toContain('check');
		expect(content).not.toContain('Foo');
	});

	it('does not overwrite when content is identical', () => {
		writeHandler(
			'user.controller.ts',
			`
import { ipcClass, ipcMethod } from 'electron-ipc-handler/main';

@ipcClass('users')
export class UserController {
	@ipcMethod()
	getAll() { return []; }
}
`
		);

		// First build
		buildPlugin();
		const firstContent = readFileSync(OUTPUT_FILE, 'utf-8');
		const { mtimeMs: mtime1 } = statSync(OUTPUT_FILE);

		// Small delay to ensure different mtime if rewritten
		const start = Date.now();
		while (Date.now() - start < 50) {
			/* busy wait */
		}

		// Second build with same content
		buildPlugin();
		const { mtimeMs: mtime2 } = statSync(OUTPUT_FILE);

		expect(mtime1).toBe(mtime2);
		expect(readFileSync(OUTPUT_FILE, 'utf-8')).toBe(firstContent);
	});

	it('handles multiple function handlers in same file', () => {
		writeHandler(
			'api.handler.ts',
			`
import { ipcHandler } from 'electron-ipc-handler/main';

export const ping = ipcHandler('system:ping', () => 'pong');
export const version = ipcHandler('system:version', () => '1.0.0');
`
		);

		buildPlugin();

		const content = readFileSync(OUTPUT_FILE, 'utf-8');

		expect(content).toContain('ping');
		expect(content).toContain('version');
		expect(content).toContain('system:');
	});

	it('generates ipc.client.ts alongside the gen file', () => {
		writeHandler(
			'user.controller.ts',
			`
import { ipcClass, ipcMethod } from 'electron-ipc-handler/main';

@ipcClass('users')
export class UserController {
	@ipcMethod()
	getAll() { return []; }
}
`
		);

		buildPlugin();

		const clientFile = join(FIXTURE_DIR, 'ipc', 'ipc.client.ts');
		expect(existsSync(clientFile)).toBe(true);

		const content = readFileSync(clientFile, 'utf-8');
		expect(content).toContain('Auto-generated by electron-ipc-handler');
		expect(content).toContain("import { createIpcClient } from 'electron-ipc-handler'");
		expect(content).toContain("import type { IpcApi } from './generated'");
		expect(content).toContain('export const ipc = createIpcClient<IpcApi>()');
	});

	it('skips generated files when scanning', () => {
		// Place a .gen.ts and ipc.client.ts in handlers dir — should be ignored
		writeHandler('ipc.gen.ts', 'export type IpcApi = {};');
		writeHandler('ipc.client.ts', 'export const ipc = {};');
		writeHandler(
			'real.ts',
			`
import { ipcHandler } from 'electron-ipc-handler/main';
export const check = ipcHandler('health:check', () => 'ok');
`
		);

		buildPlugin();

		const content = readFileSync(OUTPUT_FILE, 'utf-8');
		expect(content).toContain('check');
		// Should not contain self-referencing imports
		expect(content).not.toContain("import '../handlers/ipc.gen'");
		expect(content).not.toContain("import '../handlers/ipc.client'");
	});

	it('respects client: false option', () => {
		writeHandler(
			'user.controller.ts',
			`
import { ipcClass, ipcMethod } from 'electron-ipc-handler/main';

@ipcClass('users')
export class UserController {
	@ipcMethod()
	getAll() { return []; }
}
`
		);

		const raw = ipcDecoratorPlugin.raw(
			{ dirs: [HANDLERS_DIR], output: OUTPUT_FILE, client: false },
			{ framework: 'vite' }
		);
		const plugin = Array.isArray(raw) ? raw[0] : raw;
		if (plugin.vite?.configResolved) {
			plugin.vite.configResolved({ root: FIXTURE_DIR });
		}
		plugin.buildStart?.call({ addWatchFile: () => {} });

		expect(existsSync(OUTPUT_FILE)).toBe(true);
		const clientFile = join(FIXTURE_DIR, 'ipc', 'ipc.client.ts');
		expect(existsSync(clientFile)).toBe(false);
	});
});
