/* Auto-generated by electron-ipc-handler — DO NOT EDIT */

import './user.ipc';
import './system.ipc';

export { registerIpcDecoratorHandler } from 'electron-ipc-handler';

import type { ExtractIpcFn, InferApi } from 'electron-ipc-handler';
import type { getVersion, ping } from './system.ipc';
import type { UserIpcHandler } from './user.ipc';

export type IpcApi = InferApi<{
	users: UserIpcHandler;
}> & {
	system: {
		ping: ExtractIpcFn<typeof ping>;
		getVersion: ExtractIpcFn<typeof getVersion>;
	};
};
