/* Auto-generated by electron-ipc-handler — DO NOT EDIT */

import { createIpcClient } from 'electron-ipc-handler';
import type { IpcApi } from './ipc.gen';

export const ipc = createIpcClient<IpcApi>();
